### ISSUE TITLE
Model Weights Availability

### ISSUE THREAD

**Issue by adtserapio** [dongkyuk/CheXFusion#1]
Good day!

I was just wondering if you will make the weights available for adaptations to other medical AI use cases?

Thank you very much!

**Comment by dongkyunk** [comment]
Hi,

The model is trained on the MIMIC-CXR-JPG dataset, which includes sensitive patient medical data with restricted access. Although the dataset terms does not explicitly state anything about publicly releasing model weights, I would prefer not to because it may lead to privacy/legal problems.

The dataset is available [here](https://www.physionet.org/content/mimic-cxr-jpg/2.0.0/) if you wish to train it on your own. 

DK
